x-iiif-env: &iiif-env
  RAIS_ADDRESS: :12415
  RAIS_TILEPATH: /var/local/images
  RAIS_TILECACHELEN: 10000

x-iiif-base: &iiif-base
  image: uolibraries/rais:latest
  restart: unless-stopped
  volumes:
    - ${IMAGE_DATA_PATH}:/var/local/images:ro,Z
  expose:
    - "12415"

services:
  iiif_prod:
    <<: *iiif-base
    environment:
      <<: *iiif-env
      RAIS_IIIFURL: https://${HOST_PROD}/iiif
      RAIS_LOGLEVEL: WARN

  iiif_stage:
    <<: *iiif-base
    build:
      context: ./iiif
    environment:
      <<: *iiif-env
      RAIS_IIIFURL: https://${HOST_STAGE}/iiif
      RAIS_LOGLEVEL: DEBUG

  web:
    image: caddy:2
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - iiif_prod
      - iiif_stage
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./caddy/Caddyfile.server:/etc/caddy/Caddyfile:ro,Z
      - ./viewer/prod:/srv_prod:ro,Z
      - ./viewer/stage:/srv_stage:ro,Z
      - caddy_data:/data
      - caddy_config:/config

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro,Z
